server {
    listen 8080;
    server_name _;
    client_max_body_size 25m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /static/ {
        alias /opt/netbox/netbox/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        set $netbox_upstream http://netbox:8001;
        proxy_pass $netbox_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 75s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}
